# Generated by Django 5.1.7 on 2025-03-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rendezvous",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("heure", models.TimeField()),
                ("patient", models.CharField(max_length=100)),
                ("docteur", models.CharField(max_length=100)),
                ("motif", models.TextField()),
                ("status", models.CharField(default="en attente", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["date", "heure"],
            },
        ),
    ]
