# Generated by Django 5.0 on 2025-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="age",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_1",
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="patientprofile",
            unique_together={("last_name", "first_name")},
        ),
    ]
