# Generated by Django 5.0 on 2025-03-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patientprofile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_1",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
