# Generated by Django 5.0 on 2025-03-24 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_patientprofile_phone_number_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_1",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
