# Generated by Django 5.0 on 2025-03-24 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_alter_patientprofile_phone_number_1"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="phone_number_2",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
